defmodule OrangeCms.Repo.Migrations.CreateContentEntry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :raw_body, :text, null: false
      add :json_body, :map, null: false
      add :frontmatter, :map, default: "{}"
    end
  end

  def down do
    drop table(:content_entries)
  end
end
