defmodule OrangeCms.Repo.Migrations.ContentEntryAddRelationshipContentType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_entries) do
      add :content_type_id,
          references(:content_types,
            column: :id,
            name: "content_entries_content_type_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:content_entries, "content_entries_content_type_id_fkey")

    alter table(:content_entries) do
      remove :content_type_id
    end
  end
end