defmodule OrangeCms.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :key, :text, null: false
      add :image_settings, :map, null: false
      add :field_defs, {:array, :map}, default: "{}"
      add :anchor_field, :text, null: false
    end
  end

  def down do
    drop table(:content_types)
  end
end
