defmodule OrangeCms.Repo.Migrations.AddUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :first_name, :text
      add :last_name, :text
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :avatar, :text
      add :is_active, :boolean, default: true
      add :is_blocked, :boolean, default: false
      add :is_admin, :boolean, default: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
