defmodule OrangeCms.Repo.Migrations.AddSetupFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :setup_completed, :boolean, default: false
    end
  end

  def down do
    alter table(:projects) do
      remove :setup_completed
    end
  end
end