defmodule OrangeCms.Repo.Migrations.ContentEntryUpdateFkConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_entries) do
      modify :content_type_id, :uuid, null: false
      modify :json_body, :map, null: true
    end
  end

  def down do
    alter table(:content_entries) do
      modify :json_body, :map, null: false
      modify :content_type_id, :uuid, null: true
    end
  end
end