defmodule OrangeCms.Repo.Migrations.AddContentGithubInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_entries) do
      add :integration_info, :map
    end
  end

  def down do
    alter table(:content_entries) do
      remove :integration_info
    end
  end
end
