defmodule OrangeCms.Repo.Migrations.AddProjectUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_users_project_id_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "project_users_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:project_users, [:project_id, :user_id],
             name: "project_users_unique_project_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_users, [:project_id, :user_id],
                     name: "project_users_unique_project_user_index"
                   )

    drop constraint(:project_users, "project_users_user_id_fkey")

    drop constraint(:project_users, "project_users_project_id_fkey")

    drop table(:project_users)
  end
end