defmodule OrangeCms.Repo.Migrations.ChangeNullConstrainte do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:content_types) do
      modify :anchor_field, :text, null: true
      modify :image_settings, :map, null: true
    end
  end

  def down do
    alter table(:content_types) do
      modify :image_settings, :map, null: false
      modify :anchor_field, :text, null: false
    end
  end
end